### ISSUE TITLE
Duplicated languages after installation

### ISSUE THREAD

**Issue by jairbubbles** [SonarQubeCommunity/sonar-resharper#22]
I now have two entries for C#:
![sonarqube](https://cloud.githubusercontent.com/assets/15875066/18872999/9311fbf8-84bd-11e6-9e96-c42a76897a26.png)

Which leads to failed analysis. Here is the log:
```
2016.09.27 13:25:38 ERROR [o.s.s.c.t.CeWorkerCallableImpl] Failed to execute task AVdrYpq3JyzVkAnmiD_G
java.lang.IllegalArgumentException: Multiple entries with same key: cs=C# and cs=C#
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150) ~[guava-18.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104) ~[guava-18.0.jar:na]
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70) ~[guava-18.0.jar:na]
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254) ~[guava-18.0.jar:na]
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166) ~[guava-18.0.jar:na]
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140) ~[guava-18.0.jar:na]
```
I couldn't find where those languages are stored in the db to fix it manually.

**Comment by GregBartlett** [comment]
Possibly, I know this plugin is using the old 4.5.x plugin API and may be why sonarqube deprecated this plugin. 

I've got in my repo where I've been updating the libraries it's using and trying to fix it so it's not using deprecated methods.  Find it a little disturbing that SonarQube deprecates libraries and didn't provide the means to fix the deprecation (i.e. the RulePriority? or Severity? I can't remember now :)).  

Brought it up on their google forum and I think that's planned to be worked on in future releases.. can't remember if they said in 6.0 or not. 

Will look look into this when time permits.

**Comment by jairbubbles** [comment]
OK cool. Let me know when youhave something working.

**Comment by GregBartlett** [comment]
@jairbubbles  Is this still an issue as Sonar has been releasing updates and such, want to make sure it's not related to sonar itself before I dive into it.  Thanks!

**Comment by jairbubbles** [comment]
I didn't test recently but it seems the plugin is not maintained anyway. You can test, removing the plugin fixed the issue right away.
